version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Fusion.0.to.1"
      ACCEPT_EULA: "Y"
    expose:
     - "1433"
    ports:
     - "5020:1433"
  
  tutorial:
    build: 
      context: .
      target: tutorial
    ports:
     - "50005:50005"

  sample_hello_world:
    build: 
      context: .
      target: sample_hello_world
  sample_hello_cart:
    build: 
      context: .
      target: sample_hello_cart
  sample_hello_blazor_server:
    build: 
      context: .
      target: sample_hello_blazor_server
    ports:
     - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
  sample_blazor:
    build: 
      context: .
      target: sample_blazor
    ports:
     - "5005:5005"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5005"
      ASPNETCORE_ENVIRONMENT: "Development"
  sample_caching_server:
    build: 
      context: .
      target: sample_caching_server
    depends_on:
     - db
    links:
     - db
    expose:
     - "5010"
    ports:
     - "5010:5010"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5010"
      DB__ServerHost: "db"
      DB__ServerPort: "1433"
  sample_caching_client:
    build: 
      context: .
      target: sample_caching_client
    depends_on:
     - db
     - sample_caching_server
    links:
     - db
     - sample_caching_server
    environment:
      DB__ServerHost: "db"
      DB__ServerPort: "1433"
      Client__ServerHost: "sample_caching_server"
      Client__ServerPort: "5010"
  
  sample_blazor_ws:
    build: 
      context: .
      target: sample_blazor_ws
    ports:
     - "80:80"
    environment:
      ASPNETCORE_URLS: "http://*:80"
      Server__AssumeHttps: "true"
